Update cabal to relax upper bounds for containers and tasty
I committed this commit to fix this error.

Error: While constructing the build plan, the following exceptions were
encountered:
In the dependencies for hakyll-4.12.4.0(+buildWebsite
+checkExternal
+previewServer
+usePandoc
+watchServer):
    containers-0.6.0.1 from stack configuration does not match >=0.3 && <0.6
                       (latest matching version is 0.5.11.0)
    tasty-1.2 from stack configuration does not match >=0.11 && <1.2  (latest
              matching version is 1.1.0.4)
needed since hakyll is a build target.
Some different approaches to resolving this:
  * Set 'allow-newer: true'
    in /home/travis/.stack/config.yaml to ignore all version constraints and build anyway.
  * Consider trying 'stack solver', which uses the cabal-install solver to
    attempt to find some working build configuration. This can be convenient
    when dealing with many complicated constraint errors, but results may be
    unpredictable.
  * Recommended action: try adding the following to your extra-deps
    in /home/travis/build/Hexirp/hakyll/stack.yaml:
containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
tasty-1.1.0.4@sha256:1310ceed449b3227614b329a1672a2c5bb046cb49e281996523567b3b0ad9ecc

https://travis-ci.org/Hexirp/hakyll/builds/475694909