Update cabal to relax upper bounds for containers and pandoc
I committed this commit to fix this error. Since lrucache does not
exist in lts-13.x, I need to put lrucache in lts-13.x.

Error: While constructing the build plan, the following exceptions were
encountered:
In the dependencies for hakyll-4.12.4.0(+buildWebsite
+checkExternal
+previewServer
+usePandoc
+watchServer):
    containers-0.6.0.1 from stack configuration does not match >=0.3 && <0.6
                       (latest matching version is 0.5.11.0)
    lrucache must match >=1.1.1 && <1.3, but the stack configuration has no
             specified version  (latest matching version is 1.2.0.1)
    pandoc-2.5 from stack configuration does not match >=2.0.5 && <2.5  (latest
               matching version is 2.4)
needed since hakyll is a build target.
Some different approaches to resolving this:
  * Consider trying 'stack solver', which uses the cabal-install solver to
    attempt to find some working build configuration. This can be convenient
    when dealing with many complicated constraint errors, but results may be
    unpredictable.
  * Recommended action: try adding the following to your extra-deps
    in /home/travis/build/Hexirp/hakyll/stack.yaml:
containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
lrucache-1.2.0.1@sha256:18fc3d7052012c7ab3cd395160f34b53c5e1ec5379cc45185baf35b90ffadc2e
pandoc-2.4@sha256:f7ff25413b211d9744f6492ba0407b7768ed0a52d1b902e491074c902653744f

https://travis-ci.org/Hexirp/hakyll/builds/475668223